/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracaoRouteImport } from './routes/configuracao'
import { Route as KanbanRouteImport } from './routes/kanban'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracaoRoute = ConfiguracaoRouteImport.update({
  id: '/configuracao',
  path: '/configuracao',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/kanban': typeof KanbanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/kanban': typeof KanbanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracao': typeof ConfiguracaoRoute
  '/kanban': typeof KanbanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracao' | '/kanban'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracao' | '/kanban'
  id: '__root__' | '/' | '/configuracao' | '/kanban'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracaoRoute: typeof ConfiguracaoRoute
  KanbanRoute: typeof KanbanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracao': {
      id: '/configuracao'
      path: '/configuracao'
      fullPath: '/configuracao'
      preLoaderRoute: typeof ConfiguracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracaoRoute: ConfiguracaoRoute,
  KanbanRoute: KanbanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
